### ISSUE TITLE
How to combine multiple expressions in OR condition?

### ISSUE THREAD

**Issue by fmontorsi-equinix** [aaydin-tr/kyte#2]
Hi,
I'm looking at this library and checking if I can use it to convert some code buildings mongoDB filters.
In particular I have some code like:

```
	var orConditions []interface{}
	for _, p := range myObj {
		orCondition := datastore.Filter{
			"$and": []interface{}{
				datastore.Filter{"a": p.a},
				datastore.Filter{"b": p.b},
			},
		}

		orConditions = append(orConditions, orCondition)
	}

	// build the filter
	validFilter := datastore.Filter{
		"$or": orConditions,
	}
```

I'm missing however I can create multiple OR conditions... I would like to be able to do something like:

```
	var orConditions []kyte.filter
	for _, p := range myObj {
		orCondition := kyte.Filter().And(
				kyte.Filter().Equal("a", p.a),
				kyte.Filter().Equal("b": p.b),
			)

		orConditions = append(orConditions, orCondition)
	}

	// build the filter
	validFilter := kyte.Filter().Or(orConditions)      # this is not allowed?
```

In other words I would need to have a function like `Or(filter []*filter)`... or am I missing something?

thanks

**Comment by aaydin-tr** [comment]
Hi,

Thank you for reaching out! From what I understand, you're trying to combine multiple OR conditions using the kyte.Filter approach. You want to achieve something similar to:

```json
{
  "$or": [
    {
      "$and": [
        { "a": "value1" },
        { "b": "value2" }
      ]
    },
    {
      "$and": [
        { "a": "value3" },
        { "b": "value4" }
      ]
    },
    {
      "$and": [
        { "a": "value5" },
        { "b": "value6" }
      ]
    }
  ]
}

```

If i understand correctly, to achieve this query you can define a orFilter to combine multiple expressions. You do not need to use array of filter. Like in the example above:

```go
orFilter := kyte.Filter()
for _, p := range myObj {
	orFilter.And(
		kyte.Filter().
			Equal("a", p.a).
			Equal("b", p.b),
	)

	// simulate condition
	if false {
		orFilter.And(
			kyte.Filter().
				Equal("b", p.a).
				Equal("a", p.b),
		)
	}
}

kyte.Filter().Or(orFilter).Build()
```

If this is not the solution you're looking for, please provide a query example, and I'd be happy to assist further

**Comment by fmontorsi-equinix** [comment]
hi @aaydin-tr ,
thanks for the fast answer.
Indeed I see what you mean and that's exactly what I'm trying to achieve. I will be converting the code to "push" the AND conditions into a single kyte.Filter and then use the `kyte.Filter().Or(orFilter).Build() ` to wrap them in an OR condition.

Simplifying a bit, what was not so obvious to me is that by using:

```
        someFilter := kyte.Filter()
	someFilter.And(
		kyte.Filter().Equal("a", "value1")
	)
	someFilter.And(
		kyte.Filter().Equal("b", "value2")
	)
```

I will get:

```
{
    "$and": [
        { "a": "value1" },
      ]
    },
    {
      "$and": [
        { "b": "value2" },
      ]
    },
}
```

i.e. two different AND conditions. I was somehow expecting a _combined_ AND condition like:

```
{
    "$and": [
        { "a": "value1" },
        { "b": "value2" },
      ]
    },
}
```

Perhaps naming the method "AppendAND" (and AppendOR) would be more intuitive? not sure...

**Comment by aaydin-tr** [comment]
Hi @fmontorsi-equinix,

Thank you for your feedback! You're correct in observing that using `someFilter.And()` multiple times creates separate `$and` conditions. This behavior is intentional because `And()` and `Or()` take external filters, so each call creates a distinct condition.

The reason for this is that each `And()` or `Or()` method appends a new filter to the existing condition, rather than combining them within the same group. It allows for greater flexibility when defining complex queries with multiple layers of conditions.

I understand the naming could seem a bit unintuitive at first, but given how filters are structured, it makes sense for each call to create a new `And()` or `Or()` group.

It might be helpful to add a note about this behavior in the `README.md` to clarify how the `And()` and `Or()` method works. This could assist others in understanding how to structure their queries correctly.

I hope this clears up the confusion. Let me know if you have any more questions! 😊
